// Copyright 2026 Chernykh Valentin

#ifndef ALGORITHMS_AND_DATA_STRUCTURES_AVLTREE_H
#define ALGORITHMS_AND_DATA_STRUCTURES_AVLTREE_H

class AVLTree {
};

#endif //ALGORITHMS_AND_DATA_STRUCTURES_AVLTREE_H
