name: Windows Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest -C Release --verbose
